sudo: false
language: php

# Cache some data across builds for performance.
cache:
  apt: true
  directories:
    - node_modules

# Set the default environment.
env:
  global:
    - WP_TRAVISCI=travis:phpunit
    - WP_VERSION=latest
    - WP_MULTISITE=1

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    on_pull_requests: true
    on_success: change
    on_failure: always
    on_start: never
    on_cancel: always
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS

branches:
  only:
    - master

matrix:
  include:
    - php: 7.0
      env: WP_TRAVISCI=travis:grunt

before_script:
    - npm --version
    - node --version
    - nvm install stable
    - npm install -g grunt-cli
    - npm install
    - npm prune
    - npm --version
    - node --version

script:
    - grunt --version
    - grunt default
